import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const builtins = new Set([
	"assert", "async_hooks", "buffer", "child_process", "cluster", "console",
	"constants", "crypto", "dgram", "diagnostics_channel", "dns", "domain",
	"events", "fs", "http", "http2", "https", "inspector", "module", "net",
	"os", "path", "perf_hooks", "process", "punycode", "querystring", "readline",
	"repl", "stream", "string_decoder", "sys", "timers", "tls", "trace_events",
	"tty", "url", "util", "v8", "vm", "wasi", "worker_threads", "zlib",
]);

const prod = process.argv[2] === "production";

const ctx = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await ctx.rebuild();
	process.exit(0);
} else {
	await ctx.watch();
}