/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AnkiMarkdownSync
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ANKI_URL = "http://127.0.0.1:8765";
var DECK = "Notes::Sync";
var MODEL = "NoteSync";
var TAG = "flashcardsync";
var FENCE_RE = /```anki\s*\n([\s\S]*?)```/g;
var ID_RE = /^\s*<!--\s*id:([A-Za-z0-9_-]+)\s*-->\s*$/;
function sha256(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = h * 16777619 >>> 0;
  }
  return h.toString(16).padStart(8, "0").slice(0, 10);
}
var AnkiMarkdownSync = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = {
      ankiUrl: ANKI_URL,
      deck: DECK,
      modelName: MODEL
    };
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("refresh-cw", "Sync to Anki", () => {
      void this.syncAll();
    });
    this.addCommand({ id: "sync-all", name: "Sync vault \u2194 Anki", callback: () => void this.syncAll() });
    this.addCommand({
      id: "sync-current-file",
      name: "Sync current note to Anki",
      callback: () => {
        const v = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (v)
          void this.syncFiles([v.file]);
      }
    });
    this.addSettingTab(new SyncSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign(this.settings, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ---- AnkiConnect ----
  async anki(action, params = {}) {
    const resp = await fetch(this.settings.ankiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action, params, version: 6 })
    });
    const payload = await resp.json();
    if (payload.error)
      throw new Error(`AnkiConnect '${action}': ${payload.error}`);
    return payload.result;
  }
  async ensureDeckAndModel() {
    const models = await this.anki("modelNames");
    if (!models.includes(this.settings.modelName)) {
      await this.anki("createModel", {
        modelName: this.settings.modelName,
        inOrderFields: ["Front", "Back"],
        cardTemplates: [{ Name: "Card 1", Front: "{{Front}}", Back: "{{Front}}<hr id=answer>{{Back}}" }],
        css: ""
      });
    }
    const decks = await this.anki("deckNames");
    if (!decks.includes(this.settings.deck))
      await this.anki("createDeck", { deck: this.settings.deck });
  }
  // ---- vault scan ----
  scanVault() {
    const out = [];
    const walk = (folder, prefix = "") => {
      for (const child of folder.children) {
        if (child instanceof import_obsidian.TFolder)
          walk(child, `${prefix}${child.name}/`);
        else if (child.name.endsWith(".md")) {
          const rel = `${prefix}${child.name}`;
          const text = this.app.vault.cachedRead(this.app.vault.getAbstractFileByPath(rel));
        }
      }
    };
    walk(this.app.vault.getRoot());
    return out;
  }
  // ---- full sync over current vault files ----
  async syncFiles(paths) {
    var _a, _b, _c, _d, _e;
    await this.ensureDeckAndModel();
    const files = paths || this.app.vault.getMarkdownFiles();
    const local = /* @__PURE__ */ new Map();
    for (const f of files) {
      const text = await this.app.vault.cachedRead(f);
      const rel = f.path;
      for (const m of text.matchAll(FENCE_RE)) {
        const body = m[1];
        if (!body.includes("::"))
          continue;
        let qid;
        const lines = body.split("\n");
        if (lines.length && ID_RE.test(lines[0].trim())) {
          qid = lines[0].trim().match(ID_RE)[1];
          lines.shift();
        }
        const head = lines.join("\n").trim();
        if (!head.includes("::"))
          continue;
        const [front, ...rest] = head.split("::");
        qid = qid != null ? qid : sha256(`${rel}|${front.trim()}`);
        local.set(qid, { qid, front: front.trim(), back: rest.join("::").trim(), source: rel });
      }
    }
    const ids = await this.anki("findNotes", { query: `tag:${TAG}` });
    const infos = await this.anki("notesInfo", { notes: ids });
    const remote = /* @__PURE__ */ new Map();
    for (const info of infos) {
      const tags = info.tags || [];
      const qid = (_a = tags.find((t) => t.startsWith(`${TAG}#`))) == null ? void 0 : _a.split("#")[1];
      if (!qid)
        continue;
      remote.set(qid, {
        qid,
        front: (_c = (_b = info.fields.Front) == null ? void 0 : _b.value) != null ? _c : "",
        back: (_e = (_d = info.fields.Back) == null ? void 0 : _d.value) != null ? _e : "",
        source: "",
        ankiId: info.noteId
      });
    }
    let added = 0, updated = 0, pulled = 0;
    const toAdd = [];
    for (const [qid, card] of local) {
      const other = remote.get(qid);
      if (!other) {
        toAdd.push(card);
        added++;
      } else if (other.back !== card.back) {
        await this.anki("updateNoteFields", { note: { id: other.ankiId, fields: { Back: card.back } } });
        updated++;
      }
    }
    const inbox = [];
    for (const [qid, card] of remote) {
      if (!local.has(qid)) {
        inbox.push(`<!-- id:${qid} -->
${card.front}:: ${card.back}`);
        pulled++;
      }
    }
    if (inbox.length) {
      const inboxFile = this.app.vault.getAbstractFileByPath("_anki_inbox.md");
      const block = `

<!-- pulled from Anki ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)} -->

\`\`\`anki
${inbox.join("\n\n")}
\`\`\`
`;
      if (inboxFile instanceof import_obsidian.TFile) {
        const cur = await this.app.vault.read(inboxFile);
        await this.app.vault.modify(inboxFile, cur + block);
      } else {
        await this.app.vault.create("_anki_inbox.md", `# Anki inbox
${block}`);
      }
    }
    for (const card of toAdd) {
      await this.anki("addNote", { note: {
        deckName: this.settings.deck,
        modelName: this.settings.modelName,
        fields: { Front: card.front, Back: card.back },
        tags: [TAG, `${TAG}#${card.qid}`],
        options: { allowDuplicate: false }
      } });
    }
    new import_obsidian.Notice(`Anki Sync: +${added} added, ${updated} updated, ${pulled} pulled`);
  }
  async syncAll() {
    try {
      await this.syncFiles();
    } catch (e) {
      new import_obsidian.Notice(`Anki Sync failed: ${e.message}`);
    }
  }
};
var SyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Anki Markdown Sync" });
    new import_obsidian.Setting(containerEl).setName("AnkiConnect URL").setDesc("Default http://127.0.0.1:8765 (AnkiConnect plugin must be installed in Anki)").addText((t) => t.setValue(this.plugin.settings.ankiUrl).onChange(async (v) => {
      this.plugin.settings.ankiUrl = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Anki deck").setDesc("Destination deck, created automatically").addText((t) => t.setValue(this.plugin.settings.deck).onChange(async (v) => {
      this.plugin.settings.deck = v.trim();
      await this.plugin.saveSettings();
    }));
  }
};
