/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AnkiMarkdownSync
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ANKI_URL = "http://127.0.0.1:8765";
var DECK = "Notes::Sync";
var MODEL = "NoteSync";
var TAG = "flashcardsync";
var FENCE_RE = /```anki\s*\n([\s\S]*?)```/g;
var ID_RE = /^\s*<!--\s*id:([A-Za-z0-9_-]+)\s*-->\s*$/;
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function toHash(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = h * 16777619 >>> 0;
  }
  return h.toString(16).padStart(8, "0").slice(0, 10);
}
var AnkiMarkdownSync = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = {
      ankiUrl: ANKI_URL,
      deck: DECK,
      modelName: MODEL
    };
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("refresh-cw", "Sync to Anki", () => {
      void this.syncAll();
    });
    this.addCommand({
      id: "sync-all",
      name: "Sync vault \u2194 Anki",
      callback: () => void this.syncAll()
    });
    this.addCommand({
      id: "sync-current-file",
      name: "Sync current note to Anki",
      callback: () => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (view)
          void this.syncFiles([view.file]);
      }
    });
    this.addSettingTab(new SyncSettingTab(this.app, this));
  }
  async loadSettings() {
    const raw = await this.loadData();
    const data = isRecord(raw) ? raw : {};
    this.settings = Object.assign(this.settings, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ---- AnkiConnect ----
  async anki(action, params = {}) {
    const resp = await (0, import_obsidian.requestUrl)({
      url: this.settings.ankiUrl,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action, params, version: 6 })
    });
    const payload = resp.json;
    if (payload.error)
      throw new Error(`AnkiConnect '${action}': ${payload.error}`);
    return payload.result;
  }
  async cardQuery(query) {
    const raw = await this.anki("findNotes", { query });
    return Array.isArray(raw) ? raw : [];
  }
  async notesInfo(ids) {
    const raw = await this.anki("notesInfo", { notes: ids });
    return Array.isArray(raw) ? raw : [];
  }
  async modelNames() {
    const raw = await this.anki("modelNames");
    return Array.isArray(raw) ? raw : [];
  }
  async deckNames() {
    const raw = await this.anki("deckNames");
    return Array.isArray(raw) ? raw : [];
  }
  async ensureDeckAndModel() {
    const models = await this.modelNames();
    if (!models.includes(this.settings.modelName)) {
      await this.anki("createModel", {
        modelName: this.settings.modelName,
        inOrderFields: ["Front", "Back"],
        cardTemplates: [{ Name: "Card 1", Front: "{{Front}}", Back: "{{Front}}<hr id=answer>{{Back}}" }],
        css: ""
      });
    }
    const decks = await this.deckNames();
    if (!decks.includes(this.settings.deck))
      await this.anki("createDeck", { deck: this.settings.deck });
  }
  // ---- full sync over current vault files ----
  async syncFiles(paths) {
    var _a, _b, _c, _d;
    await this.ensureDeckAndModel();
    const files = paths || this.app.vault.getMarkdownFiles();
    const local = /* @__PURE__ */ new Map();
    for (const file of files) {
      const text = await this.app.vault.cachedRead(file);
      const rel = file.path;
      for (const match of text.matchAll(FENCE_RE)) {
        const block = match[1];
        if (!block.includes("::"))
          continue;
        let qid;
        const lines = block.split("\n");
        const first = lines[0].trim();
        const idMatch = first.match(ID_RE);
        if (idMatch) {
          qid = idMatch[1];
          lines.shift();
        }
        const head = lines.join("\n").trim();
        if (!head.includes("::"))
          continue;
        const sep = head.indexOf("::");
        const front = head.slice(0, sep).trim();
        const back = head.slice(sep + 2).trim();
        const id = qid || toHash(`${rel}|${front}`);
        local.set(id, { qid: id, front, back, source: rel });
      }
    }
    const ids = await this.cardQuery(`tag:${TAG}`);
    const infos = await this.notesInfo(ids);
    const remote = /* @__PURE__ */ new Map();
    for (const info of infos) {
      const tagged = info.tags.find((t) => t.startsWith(`${TAG}#`));
      if (!tagged)
        continue;
      const qid = tagged.split("#")[1];
      if (!qid)
        continue;
      remote.set(qid, {
        qid,
        front: (_b = (_a = info.fields.Front) == null ? void 0 : _a.value) != null ? _b : "",
        back: (_d = (_c = info.fields.Back) == null ? void 0 : _c.value) != null ? _d : "",
        source: "",
        ankiId: info.noteId
      });
    }
    let added = 0;
    let updated = 0;
    let pulled = 0;
    const toAdd = [];
    for (const [id, card] of local) {
      const other = remote.get(id);
      if (!other) {
        toAdd.push(card);
        added++;
      } else if (other.back !== card.back) {
        await this.anki("updateNoteFields", { note: { id: other.ankiId, fields: { Back: card.back } } });
        updated++;
      }
    }
    const inbox = [];
    for (const [id, card] of remote) {
      if (!local.has(id)) {
        inbox.push(`<!-- id:${id} -->
${card.front}:: ${card.back}`);
        pulled++;
      }
    }
    if (inbox.length) {
      const block = `

<!-- pulled from Anki ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)} -->

\`\`\`anki
${inbox.join("\n\n")}
\`\`\`
`;
      const inboxPath = "_anki_inbox.md";
      const existing = this.app.vault.getAbstractFileByPath(inboxPath);
      if (existing instanceof import_obsidian.TFile) {
        const current = await this.app.vault.read(existing);
        await this.app.vault.modify(existing, current + block);
      } else {
        await this.app.vault.create(inboxPath, `# Anki inbox
${block}`);
      }
    }
    for (const card of toAdd) {
      await this.anki("addNote", {
        note: {
          deckName: this.settings.deck,
          modelName: this.settings.modelName,
          fields: { Front: card.front, Back: card.back },
          tags: [TAG, `${TAG}#${card.qid}`],
          options: { allowDuplicate: false }
        }
      });
    }
    new import_obsidian.Notice(`Anki Sync: +${added} added, ${updated} updated, ${pulled} pulled`);
  }
  async syncAll() {
    try {
      await this.syncFiles();
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      new import_obsidian.Notice(`Anki Sync failed: ${message}`);
    }
  }
};
var SyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Connection").setHeading();
    new import_obsidian.Setting(containerEl).setName("AnkiConnect URL").setDesc("Default http://127.0.0.1:8765 (AnkiConnect plugin must be installed in Anki)").addText((text) => text.setValue(this.plugin.settings.ankiUrl).onChange(async (value) => {
      this.plugin.settings.ankiUrl = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Sync target").setHeading();
    new import_obsidian.Setting(containerEl).setName("Anki deck").setDesc("Destination deck, created automatically").addText((text) => text.setValue(this.plugin.settings.deck).onChange(async (value) => {
      this.plugin.settings.deck = value.trim();
      await this.plugin.saveSettings();
    }));
  }
};
